version: '3.8'

services:
  koa-api-server:
    image: node:16.19.1-bullseye
    stdin_open: true
    tty: true
    container_name: koa-api-server
    volumes:
      - /opt/koa-api-server:/opt/koa-api-server
    environment:
      DATABASE_HOSTNAME: 'postgres'
      REDIS_URL: 'redis://redis:6379/1'
      PORT: 8080
      NODE_ENV: 'development'
    depends_on:
      - postgres
      - redis
    ports:
      - 8080:8080

  postgres:
    image: postgres:15.2-bullseye
    container_name: 'postgres'
    command: postgres -c 'max_connections=200'
    environment:
        POSTGRES_PASSWORD: 'mysecretpassword'
        POSTGRES_USER: 'postgres'

  redis:
    image: 'redis:alpine'
    container_name: redis
